name: Build and Deploy to Render

on:
  push:
    branches:
      - master  # Exécuter sur chaque push sur la branche master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Étape 1: Checkout du code de TP02_ANNIS_Ricardo
      - uses: actions/checkout@v4

      # Étape 2: Installer les dépendances et créer le build
      - name: Install dependencies and build
        run: |
          npm ci
          npm run build --if-present --production

      # Étape 3: Copier les fichiers de build dans le dossier cnamApp/deployApp
      - name: Copy build files to cnamApp
        run: |
          # Vérifier si le répertoire cnamApp existe
          if [ -d "../CNAM_app/cnamApp" ]; then
              cp -r dist/tp2/* ../CNAM_app/cnamApp/deployApp/
          else
              echo "Dossier cnamApp non trouvé. Assurez-vous que CNAM_app/cnamApp existe."
              exit 1

      # Étape 4: Commit et push des fichiers dans cnamApp
      - name: Commit and push to cnamApp
        run: |
          cd ../CNAM_app/cnamApp
          git config --global user.name "Ricdrum14"
          git config --global user.email "ricardoannis9@gmail.com"
          git add .
          git commit -m "Mise à jour automatique depuis TP02_ANNIS_Ricardo"
          git push

      # Étape 5: Déployer sur Render avec le hook
      - name: Deploy to Render
        if: github.ref == 'refs/heads/master'
        env:
          deploy_url: ${{ secrets.RENDER }}
        run: |
          curl -X POST "$deploy_url"
